export const WEREWOLF_STANDARDROLES_TRANSLATE_IDS = {
    FACTION_NAME_VILLAGER: "werewolf-standardroles.faction.name.villager",
    FACTION_NAME_WEREWOLF: "werewolf-standardroles.faction.name.werewolf",
    FACTION_DESCRIPTION_VILLAGER: "werewolf-standardroles.faction.description.villager",
    FACTION_DESCRIPTION_WEREWOLF: "werewolf-standardroles.faction.description.werewolf",
    ROLE_NAME_VILLAGER: "werewolf-standardroles.role.name.villager",
    ROLE_NAME_SEER: "werewolf-standardroles.role.name.seer",
    ROLE_NAME_MEDIUM: "werewolf-standardroles.role.name.medium",
    ROLE_NAME_KNIGHT: "werewolf-standardroles.role.name.knight",
    ROLE_NAME_WEREWOLF: "werewolf-standardroles.role.name.werewolf",
    ROLE_NAME_GREATWOLF: "werewolf-standardroles.role.name.greatwolf",
    ROLE_NAME_MADMAN: "werewolf-standardroles.role.name.madman",
    ROLE_DESCRIPTION_VILLAGER: "werewolf-standardroles.role.description.villager",
    ROLE_DESCRIPTION_SEER: "werewolf-standardroles.role.description.seer",
    ROLE_DESCRIPTION_MEDIUM: "werewolf-standardroles.role.description.medium",
    ROLE_DESCRIPTION_KNIGHT: "werewolf-standardroles.role.description.knight",
    ROLE_DESCRIPTION_WEREWOLF: "werewolf-standardroles.role.description.werewolf",
    ROLE_DESCRIPTION_GREATWOLF: "werewolf-standardroles.role.description.greatwolf",
    ROLE_DESCRIPTION_MADMAN: "werewolf-standardroles.role.description.madman",
};
